---
layout: cv
title: Myungwon Lee's Resume
---
# Myungwon Lee
BYU-Idaho Data Science Student

<div id="webaddress">
<a href="ctrmyung@gmail.com">ctrmyung@gmail.com</a>
| <a href="https://www.linkedin.com/in/lee-myungwon/">LinkedIn</a> 
| <a href="https://github.com/MyungwonL">Github</a>
</div>


## Education

`Apr 2022 - present`
__Brigham Young University - Idaho__

- GPA: 4.0

- Full academic scholarship 2023-2025


## Skills

| **Technical** | **Non-Technical** |     **Language**     |
|:-------------:|:-----------------:|:--------------------:|
|     Python    |   Communication   |    Korean (Native)   |
|      SQL      |  Problem solving  | English (proficient) |
|   R, Rstudio  |      Teamwork     |                      |



## Work Experience

`May 2022 - July 2024` **Library Aide**  
*McKay Library Special Collections & Archives | BYU-Idaho*

- Created XML files to expand the online accessibility of materials to a wider audience. 

- Provided exceptional customer service by assisting patrons with inquiries and resource location. 

- Worked on various projects that require self-motivation and attention to detail. 

`May 2023 - Aug 2023` **Customer Service Representative**  
*Edunet.com | Hyosung ITX*

- Responded promptly to the requests from customers and resolved issues. 

- Recognized the need for help from other representatives and helped them find solutions. 

- Demonstrated excellent communication skills with customers and earned a reputation for a high customer satisfaction score.  

`Aug 2022 - Feb 2022` **Sergeant**  
*Republic of Korea Army*

- Led and managed a team of 15 and fostered a culture of discipline, accountability, and teamwork. 

- Facilitated clear communication skills within the team and with higher-ranking officers to implement effective problem-solving techniques. 



## Volunteering Experience

`Feb 2018 - Feb 2020` Full-time Representative (New York City, NY)  
*The Church of Jesus Christ of Latter-day Saints*

- Taught life-improving principles to hundreds of people by delivering customized lessons. 

- Collaborated with local organizations to assist with providing supplies to those in need. 

- Trained missionaries on setting goals, discipline, and effective teaching skills. 

<!-- ### Footer

Last updated: May 2013 -->